M48
; DRILL file {KiCad 9.0.6} date 2026-03-03T22:35:12+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-03T22:35:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X139.3Y-65.46
X139.3Y-71.24
T2
X48.5Y-114.0
X137.0Y-58.0
X141.5Y-114.0
T3
X49.0Y-60.0
X61.0Y-118.0
X129.0Y-118.0
X141.0Y-60.0
M30
